apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
  - name: web2 
    protocol: TCP
    port: 8000
    targetPort: 80
  - name: web3
    protocol: TCP
    port: 8080
    targetPort: 80
  clusterIP: 10.96.1.1
