apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx 
  replicas: 4 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          image: ciscolabs/nginx-gh
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
